<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{f4f0cafd-4cbb-483d-a3a6-3a1fa52891bd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bLoad 	: BOOL;
	sPath	: STRING := 'C:\Temp\TC3_SyncUnits.pdf';
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>