<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{be712938-f49c-4500-970d-9ea04678be54}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bButton : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_TrackRemainingTime();
P_LoginFromPLC();
P_ListUsers();

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>