<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="MAIN" Id="{d09a3875-155e-4b0a-83fc-897e93d6a041}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	nValueInt 	: INT;
	nValueDword : DWORD;
	fValueReal 	: REAL;
	
	sRecipe 	: STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>